config/routes.rb
Rails.application.routes.draw do
  get 'payments/success'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#home", as: "root"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"

  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get "/:path", to: "pages#not_found"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
    has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :breed
  enum sex: { female: 0, male: 1 }
  has_one_attached :picture
  belongs_to :user
  has_one :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user #user is a buyer
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :set_listing, only: [:show, :edit, :update, :destroy]
    before_action :set_breeds_and_sexes, only: [:new, :edit]
    before_action :set_user_listing, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        @listings = Listing.all
    end

    def create
        @listing = current_user.listings.create(listing_params)

        # @listing = Listing.create(listing_params)
        # console
        if @listing.errors.any?
            set_breeds_and_sexes
            render "new"
        else
            redirect_to listings_path
        end
    end

    def new 
        @listing = Listing.new
    end

    def show
        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.email,
            line_items: [{
                name: @listing.title,
                description: @listing.description,
                amount: @listing.price * 100,
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                    listing_id: @listing.id
                }
            },
            success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
            cancel_url: "#{root_url}listings"
        )

        @session_id = session.id
    end

    def update
        
        if @listing.update(listing_params)
            redirect_to @listing
        else
            render "edit"
        end
    end

    def destroy 
        
        @listing.destroy
 
        redirect_to listings_path
    end

    def edit 
        
    end

    private

    def set_listing
        id = params[:id]
        @listing = Listing.find(id)
    end
    
    def set_breeds_and_sexes
        @breeds = Breed.all
        @sexes = Listing.sexes.keys
    end

    def set_user_listing
        id = params[:id]
        @listing = current_user.listings.find_by_id(id)
    
        if @listing == nil
            redirect_to listings_path
        end
    end

    def listing_params
        params.require(:listing).permit(:title, :description, :price, :city, :state, :date_of_birth, :diet, :breed_id, :sex, :picture)
    end
end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def not_found
    render plain: "this page doesn't exist, go away!"
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]

  def success

  end

  def webhook
    # payment_id= params[:data][:object][:payment_intent]
    # payment = Stripe::PaymentIntent.retrieve(payment_id)
    # listing_id = payment.metadata.listing_id
    # user_id = payment.metadata.user_id

    # p "listing id " + listing_id
    # p "user id " + user_id
    event = Stripe::Event.construct_from(
      # p "user id " + user_id
      params.to_unsafe_h
    )

    # Handle the event
    case event.type
    when 'payment_intent.succeeded'
        payment_intent = event.data.object # contains a Stripe::PaymentIntent
        
        buyer = User.find(payment_intent.metadata.user_id)
        listing = Listing.find(payment_intent.metadata.listing_id)
        listing.bought = true
        listing.save

        order = Order.new
        order.user = buyer
        order.listing = listing
        order.save
        
        # Then define and call a method to handle the successful payment intent.
        # handle_payment_intent_succeeded(payment_intent)
    when 'payment_method.attached'
        payment_method = event.data.object # contains a Stripe::PaymentMethod
        # Then define and call a method to handle the successful attachment of a PaymentMethod.
        # handle_payment_method_attached(payment_method)
    # ... handle other event types
    else
        # Unexpected event type
        render :nothing => true, :status => :bad_request
        return
    end

    # success, but don't need to send anything back to Stripe
    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnakeMarketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%#= link_to "logout", destroy_user_session_path, method: :delete %>
    <% if user_signed_in? %>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "login", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<h1>EDIT a listing</h1>

<%= form_with(model: @listing, local: true) do |form| %>
    <div
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0 %>
    </div>
    <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>
    <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>
    <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>
    <div>
        <%= form.label :diet %>
        <%= form.text_field :diet %>
    </div>
    <div>
        <%= form.label :breed_id %>
        <%= form.select(:breed_id, @breeds.map{|b| [b.name, b.id]}) %>
    </div>

    <% @sexes.each do |option| %>
        <div>
            <%= form.radio_button :sex, option %>
            <%= form.label "sex_#{option}".to_sym, option %>
        <div>
    <% end %>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/index.html.erb
<h1>Ssssnake Listingsssssssss</h1>

<% @listings.each do |listing| %>
    <% if !listing.bought? then %>
        <p>-----------------------------</p>
        <%= image_tag listing.picture if listing.picture.attached? %>
        <p><%= listing.title %></p>
        <p><%= listing.description %></p>
        <%= link_to "edit", edit_listing_path(listing.id) if current_user.id == listing.user.id %>
        <%= link_to "show", listing_path(listing.id) %>
        <%= link_to "delete ⛔️", listing_path(listing),
                method: :delete,
                data: { confirm: "Are you sure?" } if current_user.id == listing.user.id %>
    <% end %>
<% end %>

app/views/listings/new.html.erb
<h1>List a snake!</h1>

<%= form_with(model: @listing, local: true) do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0 %>
    </div>
    <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>
    <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>
    <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>
    <div>
        <%= form.label :diet %>
        <%= form.text_field :diet %>
    </div>
    <div>
        <%= form.label :breed_id %>
        <%= form.select(:breed_id, @breeds.map{|b| [b.name, b.id]}) %>
    </div>

    <% @sexes.each do |option| %>
        <div>
            <%= form.radio_button :sex, option %>
            <%= form.label "sex_#{option}".to_sym, option %>
        <div>
    <% end %>
    <div>
        <%= form.label :picture %> <%= form.file_field :picture, accept:
                    'image/png,image/gif,image/jpeg,image/jpg' %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/show.html.erb
<div class="container">
    <h1><%= @listing.title %></h1>
    <%= image_tag @listing.picture if @listing.picture.attached? %>
    <p>Description: <%= @listing.description %></p>
    <p>Breed: <%= @listing.breed.name %></p>
    <p>Sex: <%= @listing.sex %></p>
    <p>Price: <%= @listing.price %></p>

    <button data-stripe="payment">
        Buy now <%= number_to_currency(@listing.price) %>
    </button>

    <script src="https://js.stripe.com/v3/"></script>

    <script>
    document
        .querySelector("[data-stripe='payment']")
        .addEventListener("click", () => {
        const stripe = Stripe(
            "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
        );

        stripe.redirectToCheckout({
            sessionId: "<%= @session_id %>"
        });
        });
    </script>
</div>

app/views/pages/home.html.erb
<h1>Legless Pets</h1>
<%#= image_tag "hero.jpg", alt: "Pretty snakes" %>
<div class="hero"></div>
<p>
  Find your dream snake
</p>

app/views/pages/not_found.html.erb
<h1>Pages#not_found</h1>
<p>Find me in app/views/pages/not_found.html.erb</p>

app/views/payments/success.html.erb
<h1>You've successfully made a payment! <%= link_to "Go To Listings", listings_path%></h1>